/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData list_nested = IconData(0xe800, fontFamily: _kFontFam );
  static const IconData expense = IconData(0xe801, fontFamily: _kFontFam );
  static const IconData interest = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData salary = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData budget = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData article_alt = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData scissors = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData dollar = IconData(0xf155, fontFamily: _kFontFam);
  static const IconData chart_line = IconData(0xf201, fontFamily: _kFontFam);
  static const IconData hand_holding_usd = IconData(0xf4c0, fontFamily: _kFontFam);
}
